In [1]:
import pandas as pd
import numpy as np

In [133]:
data=pd.read_csv('IndianFoodDatasetCSV.csv')

In [134]:
data.sample(1)

Srno                                         RecipeName  \
2856  3452  भोगिची भाजी रेसिपी - Bhogichi Bhaji (Recipe In...   

                               TranslatedRecipeName  \
2856  Bhogichi Bhaji Recipe (Bhogichi Bhaji Recipe)   

                                            Ingredients  \
2856  1 आलू - छीलकर काट ले,2 गाजर - लाल,3 बैंगन - का...   

                                  TranslatedIngredients  PrepTimeInMins  \
2856  1 potato - peel and chop, 2 carrots - red, 3 e...              10   

      CookTimeInMins  TotalTimeInMins  Servings                Cuisine Course  \
2856              30               40         4  Maharashtrian Recipes  Lunch   

            Diet                                       Instructions  \
2856  Vegetarian  भोगिची भाजी बनाने के लिए सबसे पहले एक कढ़ाई में...   

                                 TranslatedInstructions  \
2856  To make Bhogichi Bhaji, first heat oil in a pa...   

                                                    URL  
2856  https://www.archanaskitchen.com/bhogichi-bhaji...

In [135]:
backup_data=data

In [136]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6871 entries, 0 to 6870
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype 
---  ------                  --------------  ----- 
 0   Srno                    6871 non-null   int64 
 1   RecipeName              6871 non-null   object
 2   TranslatedRecipeName    6871 non-null   object
 3   Ingredients             6865 non-null   object
 4   TranslatedIngredients   6865 non-null   object
 5   PrepTimeInMins          6871 non-null   int64 
 6   CookTimeInMins          6871 non-null   int64 
 7   TotalTimeInMins         6871 non-null   int64 
 8   Servings                6871 non-null   int64 
 9   Cuisine                 6871 non-null   object
 10  Course                  6871 non-null   object
 11  Diet                    6871 non-null   object
 12  Instructions            6871 non-null   object
 13  TranslatedInstructions  6871 non-null   object
 14  URL                     6871 non-null   object
dtypes: i

In [137]:
mask=data["Servings"]<=20

In [138]:
data=data[mask]

In [139]:
data.shape

(6822, 15)

In [140]:
data.sample(1)

Srno                                      RecipeName  \
5602  8421  बेसिल पेस्तो रेसिपी - Fresh Basil Pesto Recipe   

           TranslatedRecipeName  \
5602   Fresh Basil Pesto Recipe   

                                            Ingredients  \
5602  250 ग्राम बेसिल के पत्ते - स्टेम निकाल ले,1/4 ...   

                                  TranslatedIngredients  PrepTimeInMins  \
5602  250 grams Basil leaves - take out the stem, 1/...              10   

      CookTimeInMins  TotalTimeInMins  Servings Cuisine  Course        Diet  \
5602              20               30        10    Thai  Dinner  Vegetarian   

                                           Instructions  \
5602  बेसिल पेस्तो रेसिपी बनाने के लिए, सबसे पहले सा...   

                                 TranslatedInstructions  \
5602  To make the Basil Pesto Recipe, first prepare ...   

                                                    URL  
5602  https://www.archanaskitchen.com/fresh-basil-pe...

In [141]:
data["TotalTimeInMins"].value_counts()

TotalTimeInMins
40     972
30     837
50     672
35     561
45     514
      ... 
67       1
795      1
455      1
600      1
58       1
Name: count, Length: 164, dtype: int64

In [142]:
cuisines = ["Indian", "Continental", "North Indian Recipes", "South Indian Recipes", "Italian Recipes"]
x = data["Cuisine"].isin(cuisines)

In [143]:
data.shape

(6822, 15)

In [144]:
cuisines = ["Indian", "Continental", "North Indian Recipes", "South Indian Recipes", "Italian Recipes"]
x = data["Cuisine"].isin(cuisines)

In [145]:
data=data[x]

In [146]:
Course = ["Lunch", "Side Dish", "Snack", "Dinner", "Appetizer","World Breakfast","Dessert","Main Course"]
x = data["Course"].isin(Course)

In [147]:
data=data[x]

In [148]:
Diet = ["Vegetarian", "High Protein Vegetarian", "Eggetarian", "Diabetic Friendly", "High Protein Non Vegetarian","Non Vegeterian"]
x = data["Diet"].isin(Diet)

In [150]:
data.shape

(3651, 15)

In [251]:
data.sample(1)

Srno                                         RecipeName  \
3892  5058  Creamy Cinnamon Peach Milkshake Recipe With Ch...   

                                   TranslatedRecipeName  \
3892  Creamy Cinnamon Peach Milkshake Recipe With Ch...   

                                            Ingredients  \
3892  5 Peaches - deseeded and sliced,2 tablespoons ...   

                                  TranslatedIngredients  PrepTimeInMins  \
3892  5 Peaches - deseeded and sliced,2 tablespoons ...              10   

      CookTimeInMins  TotalTimeInMins  Servings      Cuisine Course  \
3892               0               10         4  Continental  Snack   

            Diet                                       Instructions  \
3892  Vegetarian  To begin making Creamy Cinnamon Peach Milkshak...   

                                 TranslatedInstructions  \
3892  To begin making Creamy Cinnamon Peach Milkshak...   

                                                    URL  
3892  http://www.archanaskitchen.com/creamy-cinnamon...

In [175]:
x=data.iloc[:,7:12]

In [176]:
x=data["TotalTimeInMins"]<50

In [177]:
data=data[x]

In [178]:
data.shape

(2208, 15)

In [188]:
x=data.iloc[:,7:12]

In [189]:
data["Cuisine"].value_counts()

Cuisine
Indian                  682
Continental             569
North Indian Recipes    472
South Indian Recipes    369
Italian Recipes         116
Name: count, dtype: int64

In [190]:
x.shape

(2208, 5)

In [191]:
x

TotalTimeInMins  Servings               Cuisine       Course  \
0                  45         6                Indian    Side Dish   
1                  15         3  South Indian Recipes  Main Course   
8                  30         3  South Indian Recipes        Snack   
9                  25         3  South Indian Recipes    Side Dish   
15                 40         4  South Indian Recipes    Side Dish   
...               ...       ...                   ...          ...   
6859               30         4  North Indian Recipes        Lunch   
6860               45         4           Continental        Snack   
6863               20         4                Indian      Dessert   
6865               35         2                Indian      Dessert   
6870               40         4  North Indian Recipes        Lunch   

                         Diet  
0           Diabetic Friendly  
1                  Vegetarian  
8                  Vegetarian  
9                  Vegetarian  
15                 Vegetarian  
...                       ...  
6859  High Protein Vegetarian  
6860               Vegetarian  
6863               Vegetarian  
6865               Vegetarian  
6870  High Protein Vegetarian  

[2208 rows x 5 columns]

In [192]:
labels, unique = pd.factorize(x['Diet'])
x['Diet'] = labels
print(unique)

Index(['Diabetic Friendly', 'Vegetarian', 'Eggetarian', 'Vegan',
       'High Protein Vegetarian', 'No Onion No Garlic (Sattvic)',
       'Non Vegeterian', 'High Protein Non Vegetarian', 'Gluten Free',
       'Sugar Free Diet'],
      dtype='object')


In [193]:
labels, unique = pd.factorize(x['Course'])
x['Course'] = labels
print(unique)

Index(['Side Dish', 'Main Course', 'Snack', 'Lunch', 'Appetizer', 'Dessert',
       'Dinner', 'World Breakfast'],
      dtype='object')


In [194]:
labels, unique = pd.factorize(x['Cuisine'])
x['Cuisine'] = labels
print(unique)

Index(['Indian', 'South Indian Recipes', 'North Indian Recipes',
       'Italian Recipes', 'Continental'],
      dtype='object')


In [204]:
x

TotalTimeInMins  Servings  Cuisine  Course  Diet
0                  45         6        0       0     0
1                  15         3        1       1     1
8                  30         3        1       2     1
9                  25         3        1       0     1
15                 40         4        1       0     1
...               ...       ...      ...     ...   ...
6859               30         4        2       3     4
6860               45         4        4       2     1
6863               20         4        0       5     1
6865               35         2        0       5     1
6870               40         4        2       3     4

[2208 rows x 5 columns]

In [205]:
y=x.values
y

array([[45,  6,  0,  0,  0],
       [15,  3,  1,  1,  1],
       [30,  3,  1,  2,  1],
       ...,
       [20,  4,  0,  5,  1],
       [35,  2,  0,  5,  1],
       [40,  4,  2,  3,  4]], dtype=int64)

In [206]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
y = scaler.fit_transform(y)

In [214]:
y

array([[ 1.34768445,  1.32161124, -1.1417461 , -1.43719313, -1.04749801],
       [-1.63705654, -0.46827894, -0.50141707, -0.97339272, -0.45612097],
       [-0.14468604, -0.46827894, -0.50141707, -0.5095923 , -0.45612097],
       ...,
       [-1.1395997 ,  0.12835112, -1.1417461 ,  0.88180894, -0.45612097],
       [ 0.35277079, -1.06490899, -1.1417461 ,  0.88180894, -0.45612097],
       [ 0.85022762,  0.12835112,  0.13891196, -0.04579189,  1.31801015]])

In [201]:
from sklearn.neighbors import NearestNeighbors

In [208]:
model=NearestNeighbors(algorithm="brute")

In [209]:
model.fit(y)

NearestNeighbors(algorithm='brute')

In [223]:
dist,indx=model.kneighbors([y[1]],10)

In [215]:
x.to_csv("processeeData.csv",index=False)

In [232]:
data.reset_index()

index   Srno                                         RecipeName  \
0         0      1                               Masala Karela Recipe   
1         1      2  टमाटर पुलियोगरे रेसिपी - Spicy Tomato Rice (Re...   
2         8      9                   Spicy Crunchy Masala Idli Recipe   
3         9     10  गोभी के पत्तो की चटनी रेसिपी - Cauliflower Lea...   
4        15     16  साउथ इंडियन प्याज चटनी रेसिपी - South Indian O...   
...     ...    ...                                                ...   
2203   6859  13994  तड़के वाली मसूर दाल रेसिपी - Tadkewali Masoor D...   
2204   6860  14015                Southern Buttermilk Biscuits Recipe   
2205   6863  14030                         Saffron Paneer Peda Recipe   
2206   6865  14045        Quinoa Phirnee Recipe (Quinoa Milk Pudding)   
2207   6870  14211              नवरंग दाल रेसिपी - Navrang Dal Recipe   

                                   TranslatedRecipeName  \
0                                  Masala Karela Recipe   
1                            Spicy Tomato Rice (Recipe)   
2                      Spicy Crunchy Masala Idli Recipe   
3          Cauliflower Leaves Chutney (Recipe in Hindi)   
4     South Indian Onion Chutney Recipe - South Indi...   
...                                                 ...   
2203                        Tadkewali Masoor Dal Recipe   
2204                Southern Buttermilk Biscuits Recipe   
2205                         Saffron Paneer Peda Recipe   
2206        Quinoa Phirnee Recipe (Quinoa Milk Pudding)   
2207                                 Navrang Dal Recipe   

                                            Ingredients  \
0     6 Karela (Bitter Gourd/ Pavakkai) - deseeded,S...   
1     2-1/2 कप चावल - पका ले,3 टमाटर,3 छोटा चमच्च बी...   
2     10 Idli - cut into strips,1 cup Green Bell Pep...   
3     1 कप गोभी के पत्ते,3/4 कप टमाटर,18 ग्राम इमली,...   
4     2 प्याज,1 छोटा चमच्च जीरा,2 बड़े चमच्च काली उरद...   
...                                                 ...   
2203  1 बड़ा चम्मच घी,1/4 छोटा चम्मच हींग,1 प्याज - ब...   
2204  1 cup All Purpose Flour (Maida),1 teaspoon Bak...   
2205  2 cups Paneer (Homemade Cottage Cheese) - crum...   
2206  1 cup Quinoa,3/4 cup Sugar,1 teaspoon Cardamom...   
2207  2 बड़े चम्मच हरी मूंग दाल,2 बड़े चम्मच सफ़ेद उरद ...   

                                  TranslatedIngredients  PrepTimeInMins  \
0     6 Karela (Bitter Gourd/ Pavakkai) - deseeded,S...              15   
1     2-1 / 2 cups rice - cooked, 3 tomatoes, 3 teas...               5   
2     10 Idli - cut into strips,1 cup Green Bell Pep...              10   
3     1 cup cabbage leaves, 3/4 cup tomatoes, 18 gra...               5   
4     2 onions, 1 teaspoon cumin seeds, 2 tablespoon...              20   
...                                                 ...             ...   
2203  1 बड़ा चम्मच घी,1/4 छोटा चम्मच हींग,1 प्याज - ब...              10   
2204  1 cup All Purpose Flour (Maida),1 teaspoon Bak...              20   
2205  2 cups Paneer (Homemade Cottage Cheese) - crum...               5   
2206  1 cup Quinoa,3/4 cup Sugar,1 teaspoon Cardamom...              10   
2207  2 बड़े चम्मच हरी मूंग दाल,2 बड़े चम्मच सफ़ेद उरद ...              10   

      CookTimeInMins  TotalTimeInMins  Servings               Cuisine  \
0                 30               45         6                Indian   
1                 10               15         3  South Indian Recipes   
2                 20               30         3  South Indian Recipes   
3                 20               25         3  South Indian Recipes   
4                 20               40         4  South Indian Recipes   
...              ...              ...       ...                   ...   
2203              20               30         4  North Indian Recipes   
2204              25               45         4           Continental   
2205              15               20         4                Indian   
2206              25               35         2                Indian   
2207   

In [238]:
indx[0]

array([   1,  606,  750, 2190, 1713,  962, 1338,  800,  184,  538],
      dtype=int64)

In [241]:
data.iloc[indx[0]]

Srno                                         RecipeName  \
1         2  टमाटर पुलियोगरे रेसिपी - Spicy Tomato Rice (Re...   
1917   2202         Spicy Tomato Rice - Tomato Pulihora Recipe   
2359   2752  Kothamalli Thogayal Recipe | Coriander Leaves ...   
6825  13525  कोथामली थोगयल रेसिपी - Kothamalli Thogayal Recipe   
5397   7921                      Cabbage Tomato Pachadi Recipe   
3021   3679        Sun Dried Raw Mango Raita Recipe-Ambula Rai   
4232   5614  Vazaithandu Neer Mor Recipe - Plantain Stem Bu...   
2524   2976        कोल्लु थोगयल रेसिपी - Kollu Thogayal Recipe   
624     675  कोल्लु थोगयल - Horsegram Chutney (Recipe In Hi...   
1726   1968  Tomato Onion Chutney Recipe With Coconut And Mint   

                                   TranslatedRecipeName  \
1                            Spicy Tomato Rice (Recipe)   
1917         Spicy Tomato Rice - Tomato Pulihora Recipe   
2359  Kothamalli Thogayal Recipe | Coriander Leaves ...   
6825                         Kothamalli Thogayal Recipe   
5397                      Cabbage Tomato Pachadi Recipe   
3021        Sun Dried Raw Mango Raita Recipe-Ambula Rai   
4232  Vazaithandu Neer Mor Recipe - Plantain Stem Bu...   
2524                              Kollu Thogayal Recipe   
624                 Horsegram Chutney (Recipe In Hindi)   
1726  Tomato Onion Chutney Recipe With Coconut And Mint   

                                            Ingredients  \
1     2-1/2 कप चावल - पका ले,3 टमाटर,3 छोटा चमच्च बी...   
1917  2-1/2 cups Cooked rice,3 Tomatoes,3 teaspoons ...   
2359  1 cup Coriander (Dhania) Leaves,2 tablespoons ...   
6825  1 कप हरा धनिया,2 बड़े चम्मच नारियल,6 सुखी लाल म...   
5397  1 Tomato - chopped,1 cup Cabbage (Patta Gobi/ ...   
3021  6 Dry Green Mango (Vathal/ Ambula) - pieces,1/...   
4232  1 Plantain Stem - (small),Water - as required,...   
2524  3 कुलीथ दाल,1 बड़ा चम्मच चना दाल,1 बड़ा चम्मच उर...   
624   3 कुलीथ दाल,1 बड़ा चमच्च चना दाल,1 बड़ा चमच्च का...   
1726  2 Onions,2 Tomatoes,2 Green Chillies,10 Mint L...   

                                  TranslatedIngredients  PrepTimeInMins  \
1     2-1 / 2 cups rice - cooked, 3 tomatoes, 3 teas...               5   
1917  2-1/2 cups Cooked rice,3 Tomatoes,3 teaspoons ...               5   
2359  1 cup Coriander (Dhania) Leaves,2 tablespoons ...              10   
6825  1 कप हरा धनिया,2 बड़े चम्मच नारियल,6 सुखी लाल म...              10   
5397  1 Tomato - chopped,1 cup Cabbage (Patta Gobi/ ...               5   
3021  6 Dry Green Mango (Vathal/ Ambula) - pieces,1/...              10   
4232  1 Plantain Stem - (small),Water - as required,...              15   
2524  3 कुलीथ दाल,1 बड़ा चम्मच चना दाल,1 बड़ा चम्मच उर...               5   
624   3 कुलीथ दाल,1 बड़ा चमच्च चना दाल,1 बड़ा चमच्च का...               5   
1726  2 Onions,2 Tomatoes,2 Green Chillies,10 Mint L...               5   

      CookTimeInMins  TotalTimeInMins  Servings               Cuisine  \
1                 10               15         3  South Indian Recipes   
1917              10               15         3  South Indian Recipes   
2359               5               15         3  South Indian Recipes   
6825               5               15         3  South Indian Recipes   
5397              10               15         3  South Indian Recipes   
3021               1               11         3  South Indian Recipes   
4232               0               15         2  South Indian Recipes   
2524              10               15         4  South Indian Recipes   
624               10               15         4  South Indian Recipes   
1726              10               15         4  South Indian Recipes   

           Course        Diet  \
1     Main Course  Vegetarian   
1917  Main Course  Vegetarian   
2359    Side Dish  Vegetarian   
6825    Side Dish  Vegetarian   
5397    Side Dish  Vegetarian   
3021    Side Dish  Vegetarian   
4232        Snack  Vegetarian   
2524    Side Dish  Vegetarian   
624     Side Dish  Vegetarian   
1726    Side Dish  V

In [237]:
indx

array([[   1,  606,  750, 2190, 1713,  962, 1338,  800,  184,  538]],
      dtype=int64)

In [243]:
data.sample()

Srno                            RecipeName  \
2658  3163  South Indian Style Fish Curry Recipe   

                      TranslatedRecipeName  \
2658  South Indian Style Fish Curry Recipe   

                                            Ingredients  \
2658  400 Grams Fish fillet - used salmon fillet her...   

                                  TranslatedIngredients  PrepTimeInMins  \
2658  400 Grams Fish fillet - used salmon fillet her...              20   

      CookTimeInMins  TotalTimeInMins  Servings               Cuisine Course  \
2658              20               40         4  South Indian Recipes  Lunch   

                Diet                                       Instructions  \
2658  Non Vegeterian  To begin making the South Indian Style Fish Cu...   

                                 TranslatedInstructions  \
2658  To begin making the South Indian Style Fish Cu...   

                                                    URL  
2658  https://www.archanaskitchen.com/south-indian-s...

In [247]:
data["Course"].unique()

array(['Side Dish', 'Main Course', 'Snack', 'Lunch', 'Appetizer',
       'Dessert', 'Dinner', 'World Breakfast'], dtype=object)

In [246]:
data["Servings"].value_counts()

Servings
4     1347
2      459
3      151
6       79
5       61
1       35
10      31
8       25
15       7
12       5
16       2
7        2
20       2
9        1
14       1
Name: count, dtype: int64

In [249]:
x["Diet"].unique()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)